# -*- coding: utf-8 -*-
# from plone.app.textfield import RichText
# from plone.autoform import directives
from plone.dexterity.content import Container

# from plone.namedfile import field as namedfile
from plone.supermodel import model
from plone.supermodel.directives import fieldset

# from z3c.form.browser.radio import RadioFieldWidget
# from zope import schema
from zope import schema
from edi.jsonforms import _
from zope.interface import implementer

# from edi.jsonforms import _


class IForm(model.Schema):
    """Marker interface and Dexterity Python Schema for Form"""

    fieldset(
        "developer",
        label=_("Developer Fields"),
        fields=["json_schema_rev", "ui_schema_rev"],
    )
    json_schema_rev = schema.SourceText(
        title=_("JSON-Schema"),
        required=False,
        description=_(
            "The contents of this field are autogenerated on save with change note. Do not edit it manually."
        ),
    )
    ui_schema_rev = schema.SourceText(
        title=_("UI-Schema"),
        required=False,
        description=_(
            "The contents of this field are autogenerated on save with change note. Do not edit it manually."
        ),
    )


@implementer(IForm)
class Form(Container):
    """ """
